apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: stackquiz
    environment: development    
  name: stackquiz-dev-rc
  namespace: default
spec:
  replicas: 1
  selector:
    app: stackquiz
    environment: development 
  template:
    metadata:
      labels:
        app: stackquiz
        environment: development    
        deployment: ::VER::  
    spec:
      containers:
      - image: docker-registry.ds.stackexchange.com/pgrace/sei-stackquiz:latest
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 5 
        name: stackquiz
        ports:
        - containerPort: 3000
          protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
