apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: stackquiz
    environment: development    
  name: stackquiz-dev-rc-::BUILDNUM::
  namespace: default
spec:
  replicas: 1
  selector:
    app: stackquiz
    environment: development 
    commit: "::COMMIT::"
    buildTimestamp: "::TIMESTAMP::"
  template:
    metadata:
      labels:
        app: stackquiz
        environment: development    
        commit: "::COMMIT::"
        buildTimestamp: "::TIMESTAMP::"
    spec:
      containers:
      - image: docker-registry.ds.stackexchange.com/pgrace/sei-stackquiz:latest
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /_health
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 120
          timeoutSeconds: 15 
        name: stackquiz
        ports:
        - containerPort: 3000
          protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
